#!/usr/bin/env python3
"""Generate the Keccak-256 implementation and its refinement proofs.

The state keeps each 64-bit lane as its even and its odd bits in two U32s (bit
interleaving, as in XKCP's 32-bit implementations), so that each lane rotation
is two 32-bit rotations, and keeps six lanes complemented (lane complementing),
which removes most NOTs from chi.

Outputs (paths relative to the repository root):
  src/types.bend            is written by hand; src/*.bend below import it
  src/permutation.bend      round constants, rounds, the fused permutation
  src/lane.bend             word <-> interleaved lane conversion, absorb, squeeze
  src/keccak.bend           the sponge over packed little-endian words
  spec/interleave.bend      the representation relation (bit shuffles)
  proofs/permutation.bend   the permutation and the conversions against spec/
  proofs/sponge.bend        the public API against spec/sponge.bend

Every per-bit fact is discharged by a generated Bool lemma proven by case analysis;
the symbolic evaluator below mirrors Base's reduction rules (Bool.and/or/xor/not
reduce on a constructor in their first argument only) to state those lemmas.
"""
import itertools
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HEADER = "# GENERATED by tools/generate_impl.py; do not edit."

# ---------------------------------------------------------------------------
# Keccak tables

# Theta, rho and pi: b[dest] = rol R (a[src] ^ d[src % 5]).
RHO = [
    (0, 0, 0), (10, 1, 1), (20, 2, 62), (5, 3, 28), (15, 4, 27),
    (16, 5, 36), (1, 6, 44), (11, 7, 6), (21, 8, 55), (6, 9, 20),
    (7, 10, 3), (17, 11, 10), (2, 12, 43), (12, 13, 25), (22, 14, 39),
    (23, 15, 41), (8, 16, 45), (18, 17, 15), (3, 18, 21), (13, 19, 8),
    (14, 20, 18), (24, 21, 2), (9, 22, 61), (19, 23, 56), (4, 24, 14),
]
B = {dest: (src, r) for dest, src, r in RHO}
ROTS = sorted({r for _, _, r in RHO} | {1})

RC = [
    0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000,
    0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009,
    0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A,
    0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003,
    0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A,
    0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008,
]

# Lane complementing (after XKCP): these lanes are held complemented,
# and chi output k takes one of these shapes over x = b[k], y = b[k+1],
# z = b[k+2] of its row: (not x, op, not y, not z), result x ^ (y op z).
COMPLEMENTED = {1, 2, 8, 12, 17, 20}
CHI = {
    0: (0, "or", 0, 0), 1: (0, "or", 1, 0), 2: (0, "and", 0, 0), 3: (0, "or", 0, 0), 4: (0, "and", 0, 0),
    5: (0, "or", 0, 0), 6: (0, "and", 0, 0), 7: (0, "or", 0, 1), 8: (0, "or", 0, 0), 9: (0, "and", 0, 0),
    10: (0, "or", 0, 0), 11: (0, "and", 0, 0), 12: (0, "and", 1, 0), 13: (1, "or", 0, 0), 14: (0, "and", 0, 0),
    15: (0, "and", 0, 0), 16: (0, "or", 0, 0), 17: (0, "or", 1, 0), 18: (1, "and", 0, 0), 19: (0, "or", 0, 0),
    20: (0, "and", 1, 0), 21: (1, "or", 0, 0), 22: (0, "and", 0, 0), 23: (0, "or", 0, 0), 24: (0, "and", 0, 0),
}


def row3(k):
    y = k - k % 5
    return k, y + (k - y + 1) % 5, y + (k - y + 2) % 5


def split(v):
    e = o = 0
    for k in range(32):
        e |= ((v >> (2 * k)) & 1) << k
        o |= ((v >> (2 * k + 1)) & 1) << k
    return e, o


# ---------------------------------------------------------------------------
# Symbolic Bool / Word evaluation, mirroring Base.

T, F = ("c", True), ("c", False)


def var(n):
    return ("v", n)


def bnot(a):
    if a[0] == "c":
        return ("c", not a[1])
    return ("not", a)


def bxor(a, b):
    if a == F:
        return b
    if a == T:
        return bnot(b)
    return ("xor", a, b)


def band(a, b):
    if a == F:
        return F
    if a == T:
        return b
    return ("and", a, b)


def bor(a, b):
    if a == F:
        return b
    if a == T:
        return T
    return ("or", a, b)


def lit(n):
    return [("c", bool((n >> i) & 1)) for i in range(32)]


def wvar(p, off=0):
    return [var(f"{p}{off + i}") for i in range(32)]


def w_not(a):
    return [bnot(x) for x in a]


def w_xor(a, b):
    return [bxor(x, y) for x, y in zip(a, b)]


def w_and(a, b):
    return [band(x, y) for x, y in zip(a, b)]


def w_or(a, b):
    return [bor(x, y) for x, y in zip(a, b)]


def w_shln(a, n):
    return [F] * n + a[: 32 - n] if n else a


def w_shrn(a, n):
    return a[n:] + [F] * n if n else a


def w_rot(a, m):
    return a if m == 0 else w_or(w_shln(a, m), w_shrn(a, 32 - m))


def bshow(e):
    t = e[0]
    if t == "c":
        return "True{}" if e[1] else "False{}"
    if t == "v":
        return e[1]
    if t == "not":
        return f"Bool.not({bshow(e[1])})"
    return f"Bool.{t}({bshow(e[1])},{bshow(e[2])})"


def bvars(e, acc):
    if e[0] == "v":
        if e[1] not in acc:
            acc.append(e[1])
    elif e[0] != "c":
        for x in e[1:]:
            bvars(x, acc)
    return acc


def bsubst(e, m):
    if e[0] == "v":
        return m[e[1]]
    if e[0] == "c":
        return e
    return (e[0],) + tuple(bsubst(x, m) for x in e[1:])


def beval(e, env):
    t = e[0]
    if t == "c":
        return e[1]
    if t == "v":
        return env[e[1]]
    if t == "not":
        return not beval(e[1], env)
    a, b = beval(e[1], env), beval(e[2], env)
    return {"xor": a != b, "and": a and b, "or": a or b}[t]


class Bools:
    """Generated Bool lemmas, one per distinct (lhs, rhs) shape."""

    def __init__(self, prefix):
        self.prefix = prefix
        self.lemmas = {}
        self.out = []

    def prove(self, lhs, rhs):
        """A proof term of {lhs == rhs : Bool}."""
        if lhs == rhs:
            return "{==}"
        names = bvars(rhs, bvars(lhs, []))
        canon = {n: var(f"x{i}") for i, n in enumerate(names)}
        cl, cr = bsubst(lhs, canon), bsubst(rhs, canon)
        key = (cl, cr)
        if key not in self.lemmas:
            k = len(names)
            for vals in itertools.product([False, True], repeat=k):
                env = {f"x{i}": v for i, v in enumerate(vals)}
                if beval(cl, env) != beval(cr, env):
                    raise ValueError(f"false bit identity {bshow(cl)} == {bshow(cr)}")
            name = f"{self.prefix}{len(self.lemmas)}"
            self.lemmas[key] = name
            params = [f"x{i}" for i in range(k)]
            L = [f"law {name}:"]
            L += [f"  for {p}: Bool" for p in params]
            L.append(f"  {{{bshow(cl)} == {bshow(cr)} : Bool}}")
            L.append("")
            L.append(f"def {name}({','.join(params)}):")
            if k == 0:
                L.append("  {==}")
            else:
                L.append(f"  match {' '.join(params)}:")
                for vals in itertools.product(["False{}", "True{}"], repeat=k):
                    L.append(f"    case {' '.join(vals)}: {{==}}")
            L.append("")
            self.out += L
        return f"{self.lemmas[key]}({','.join(names)})"

    def ext(self, x, y, lhs, rhs):
        """ext32(x, y, ...) proving {x == y : U32} from their symbolic bits."""
        hs = [self.prove(a, b) for a, b in zip(lhs, rhs)]
        return f"X.ext32({x},{y},{','.join(hs)})"


def upat(p, off=0):
    s = "WNil{}"
    for i in reversed(range(32)):
        s = f"WCon{{{p}{off + i},{s}}}"
    return "U32{" + s + "}"


def uword(bits):
    s = "WNil{}"
    for b in reversed(bits):
        s = f"WCon{{{b},{s}}}"
    return "U32{" + s + "}"


def lpat(p):
    """A lane blasted into bits p0..p63 (lo is p0..p31)."""
    return f"T.W{{{upat(p, 0)},{upat(p, 32)}}}"


def lwords(p):
    return wvar(p, 0), wvar(p, 32)


# Mirrors of the lane-level functions -----------------------------------------

def ie_w(lo, hi):
    return [lo[2 * k] for k in range(16)] + [hi[2 * k] for k in range(16)]


def io_w(lo, hi):
    return [lo[2 * k + 1] for k in range(16)] + [hi[2 * k + 1] for k in range(16)]


def spec_rol(lo, hi, r):
    """spec/permutation.bend rotate."""
    if r == 0:
        return lo, hi
    if r < 32:
        return (w_or(w_shln(lo, r), w_shrn(hi, 32 - r)), w_or(w_shln(hi, r), w_shrn(lo, 32 - r)))
    q = r - 32
    return (w_or(w_shln(hi, q), w_shrn(lo, 32 - q)), w_or(w_shln(lo, q), w_shrn(hi, 32 - q)))


def impl_rot(e, o, r):
    if r % 2 == 0:
        return w_rot(e, r // 2), w_rot(o, r // 2)
    return w_rot(o, r // 2 + 1), w_rot(e, r // 2)


def spec_chi(a, b, c):
    return w_xor(a, w_and(w_xor(b, lit(0xFFFFFFFF)), c))


def impl_chi(k, a, b, c):
    nx, op, ny, nz = CHI[k]
    f = w_or if op == "or" else w_and
    return w_xor(w_not(a) if nx else a, f(w_not(b) if ny else b, w_not(c) if nz else c))


def mx(w, m):
    return w_not(w) if m else w


# ---------------------------------------------------------------------------
# Bend text helpers for the implementation

def rot(v, m):
    if m == 0:
        return v
    return f"U32.or(U32.shln({v},{m}n),U32.shrn({v},{32 - m}n))"


def xor(a, b):
    return f"U32.xor({a},{b})"


def neg(v, n):
    return f"U32.not({v})" if n else v


def chi_k(k, a, b, c):
    nx, op, ny, nz = CHI[k]
    return f"U32.xor({neg(a, nx)},U32.{op}({neg(b, ny)},{neg(c, nz)}))"


def round_body(ins, rce, rco, tag, indent="      "):
    L = []
    for x in range(5):
        for p, s in ((0, "e"), (1, "o")):
            L.append(f"+c{x}{s}{tag} = " + xor(ins[x][p], xor(ins[x + 5][p], xor(ins[x + 10][p], xor(ins[x + 15][p], ins[x + 20][p])))))
    for x in range(5):
        cp, cn = (x - 1) % 5, (x + 1) % 5
        L.append(f"+d{x}e{tag} = " + xor(f"c{cp}e{tag}", rot(f"c{cn}o{tag}", 1)))
        L.append(f"+d{x}o{tag} = " + xor(f"c{cp}o{tag}", f"c{cn}e{tag}"))
    outs = [None] * 25
    for row in range(5):
        for dest in range(5 * row, 5 * row + 5):
            src, r = B[dest]
            x = src % 5
            ae, ao = xor(ins[src][0], f"d{x}e{tag}"), xor(ins[src][1], f"d{x}o{tag}")
            if r % 2 == 0:
                be, bo = rot(ae, r // 2), rot(ao, r // 2)
            else:
                be, bo = rot(ao, r // 2 + 1), rot(ae, r // 2)
            L.append(f"+b{dest}e{tag} = {be}")
            L.append(f"+b{dest}o{tag} = {bo}")
        for dest in range(5 * row, 5 * row + 5):
            _, i1, i2 = row3(dest)
            for s in "eo":
                v = chi_k(dest, f"b{dest}{s}{tag}", f"b{i1}{s}{tag}", f"b{i2}{s}{tag}")
                if dest == 0:
                    v = xor(v, rce if s == "e" else rco)
                L.append(f"+q{dest}{s}{tag} = {v}")
            outs[dest] = (f"q{dest}e{tag}", f"q{dest}o{tag}")
    return [indent + l for l in L], outs


def plus_fields(p=""):
    return ",".join(f"+{p}e{k},+{p}o{k}" for k in range(25))


def st_fields(p=""):
    return ",".join(f"{p}e{k},{p}o{k}" for k in range(25))



# ---------------------------------------------------------------------------
# src/permutation.bend

def gen_perm():
    o = [HEADER, "#",
         "# Keccak-f[1600] on bit-interleaved, partly complemented lanes. Lane k =",
         "# x + 5y is held as (e{k}, o{k}), its even and its odd bits, so every",
         "# 64-bit rotation is two 32-bit rotations; lanes 1, 2, 8, 12, 17, 20 are",
         "# held complemented, which removes most NOTs from chi. `steps` fuses two",
         "# rounds per step; `rounds` is the same permutation on plain lanes.",
         "import Base",
         "import ./types.bend as T",
         "import ./lane.bend as L", "",
         "# The zero state, with the complemented lanes all ones.",
         "def initial() -> T.St:",
         "  T.St{" + ",".join(("4294967295" if k in COMPLEMENTED else "0") for k in range(25) for _ in "eo") + "}", ""]
    for s, idx in (("e", 0), ("o", 1)):
        o.append(f"# Round constants, interleaved: their {'even' if s == 'e' else 'odd'} bits.")
        o.append(f"def rc{s}(i: Nat) -> U32:")
        o.append("  match i:")
        for i, c in enumerate(RC):
            o.append(f"    case {i}n: {split(c)[idx]}")
        o.append("    case _: 0")
        o.append("")
    ins = [(f"e{k}", f"o{k}") for k in range(25)]
    o.append("def round(s: T.St, +rce: U32, +rco: U32) -> T.St:")
    o.append("  match s:")
    o.append("    case T.St{" + plus_fields() + "}:")
    L, outs = round_body(ins, "rce", "rco", "")
    o += L
    o.append("      T.St{" + ",".join(f"{e},{od}" for e, od in outs) + "}")
    o.append("")
    o.append("def rounds_short(n: Nat, +i: Nat, s: T.St) -> T.St:")
    o.append("  match n:")
    o.append("    case 0n: s")
    o.append("    case 1n+p: rounds_short(p,1n+i,round(s,rce(i),rco(i)))")
    o.append("")
    o.append("# n rounds from round i, two fused per step.")
    o.append("def steps(n: Nat, +i: Nat, s: T.St) -> T.St:")
    o.append("  match n s:")
    o.append("    case 0n s: s")
    o.append("    case 1n s: rounds_short(1n,i,s)")
    o.append("    case 2n+p T.St{" + plus_fields() + "}:")
    o.append("      +r0e = rce(i)")
    o.append("      +r0o = rco(i)")
    L, mid = round_body(ins, "r0e", "r0o", "r0")
    o += L
    o.append("      +r1e = rce(1n+i)")
    o.append("      +r1o = rco(1n+i)")
    L, outs = round_body(mid, "r1e", "r1o", "r1")
    o += L
    o.append("      steps(p,2n+i,T.St{" + ",".join(f"{e},{od}" for e, od in outs) + "})")
    o.append("")
    o += ["# n rounds from round i on a plain state.",
          "def rounds(n: Nat, +i: Nat, s: T.State) -> T.State:",
          "  L.leave(steps(n,i,L.enter(s)))", "",
          "def permute(s: T.State) -> T.State:",
          "  rounds(24n,0n,s)", ""]
    return "\n".join(o)


# ---------------------------------------------------------------------------
# src/lane.bend

STAGES = [(1, 0x22222222), (2, 0x0C0C0C0C), (4, 0x00F000F0), (8, 0x0000FF00)]


def stage_w(x, k, m):
    t = w_and(lit(m), w_xor(x, w_shrn(x, k)))
    return w_xor(w_xor(x, t), w_shln(t, k))


def stage_perm(k, m):
    """The bit permutation computed by a stage: out[i] = in[perm[i]]."""
    perm = []
    for i in range(32):
        hits = [j for j in range(32) if (stage_int(1 << j, k, m) >> i) & 1]
        assert len(hits) == 1
        perm.append(hits[0])
    return perm


def stage_int(x, k, m):
    t = (x ^ (x >> k)) & m
    return (x ^ t ^ (t << k)) & 0xFFFFFFFF


def ub_entry(b, k):
    v = 0
    for j in range(4):
        v |= ((b >> (2 * j)) & 1) << (4 * k + j)
        v |= ((b >> (2 * j + 1)) & 1) << (16 + 4 * k + j)
    return v


BYTE_SEL = ["U32.and(255,x)", "U32.and(255,U32.shrn(x,8n))", "U32.and(255,U32.shrn(x,16n))", "U32.shrn(x,24n)"]


def compose(*perms):
    """perm of applying perms[0] first."""
    idx = list(range(32))
    for p in perms:
        idx = [idx[p[i]] for i in range(32)]
    return idx



def gen_lane():
    o = [HEADER, "#",
         "# Conversions between little-endian words and interleaved lanes. unz moves",
         "# a word's even bits to its low half and its odd bits to its high half by",
         "# four byte tables; zip undoes it by four delta swaps. Masks are written",
         "# first in each AND so that the proofs reduce.",
         "import Base",
         "import ./types.bend as T", ""]
    for k, m in STAGES:
        o.append(f"def swap{k}(+x: U32) -> U32:")
        o.append(f"  +t = U32.and({m},U32.xor(x,U32.shrn(x,{k}n)))")
        o.append(f"  U32.xor(U32.xor(x,t),U32.shln(t,{k}n))")
        o.append("")
    for k in range(4):
        o.append(f"# unz of byte {k} of a word: its even bits at 4*{k}.., its odd bits at 16+4*{k}..")
        o.append(f"def ub{k}(n: Nat) -> U32:")
        o.append("  match n:")
        for b in range(256):
            o.append(f"    case {b}n: {ub_entry(b, k)}")
        o.append("    case _: 0")
        o.append("")
    o += ["# The even bits of x in its low half, the odd bits in its high half.",
          "def unz(+x: U32) -> U32:",
          "  U32.or(U32.or(ub0(U32.to_nat(U32.and(255,x))),ub1(U32.to_nat(U32.and(255,U32.shrn(x,8n))))),U32.or(ub2(U32.to_nat(U32.and(255,U32.shrn(x,16n)))),ub3(U32.to_nat(U32.shrn(x,24n)))))", "",
          "# unz's inverse.",
          "def zip(+x: U32) -> U32:",
          "  swap1(swap2(swap4(swap8(x))))", "",
          "# The even and the odd bits of a lane, from the unz of its low and high words.",
          "def even(+ul: U32, +uh: U32) -> U32:",
          "  U32.or(U32.and(65535,ul),U32.shln(uh,16n))", "",
          "def odd(+ul: U32, +uh: U32) -> U32:",
          "  U32.or(U32.shrn(ul,16n),U32.and(4294901760,uh))", "",
          "# The low and the high word of the lane with even bits e, odd bits o.",
          "def low(+e: U32, +o: U32) -> U32:",
          "  zip(U32.or(U32.and(65535,e),U32.shln(o,16n)))", "",
          "def high(+e: U32, +o: U32) -> U32:",
          "  zip(U32.or(U32.shrn(e,16n),U32.and(4294901760,o)))", ""]
    # enter / leave: whole states
    o.append("# A plain state in the interleaved representation.")
    o.append("def enter(s: T.State) -> T.St:")
    o.append("  match s:")
    o.append("    case T.S{" + ",".join(f"T.W{{+x{k},+y{k}}}" for k in range(25)) + "}:")
    fs = []
    for k in range(25):
        e, od = f"even(unz(x{k}),unz(y{k}))", f"odd(unz(x{k}),unz(y{k}))"
        if k in COMPLEMENTED:
            e, od = f"U32.not({e})", f"U32.not({od})"
        fs += [e, od]
    o.append("      T.St{" + ",".join(fs) + "}")
    o.append("")
    o.append("# enter's inverse.")
    o.append("def leave(s: T.St) -> T.State:")
    o.append("  match s:")
    o.append("    case T.St{" + plus_fields() + "}:")
    lanes = []
    for k in range(25):
        e, od = (f"U32.not(e{k})", f"U32.not(o{k})") if k in COMPLEMENTED else (f"e{k}", f"o{k}")
        lanes.append(f"T.W{{low({e},{od}),high({e},{od})}}")
    o.append("      T.S{" + ",".join(lanes) + "}")
    o.append("")
    ws = ",".join(f"w{i}: U32" for i in range(34))
    o.append("# A block's 34 words XORed into the first 17 lanes.")
    o.append(f"def mix(s: T.St,{ws}) -> T.St:")
    o.append("  match s:")
    o.append("    case T.St{" + plus_fields() + "}:")
    for j in range(17):
        o.append(f"      +l{j} = unz(w{2 * j})")
        o.append(f"      +h{j} = unz(w{2 * j + 1})")
    fs = []
    for k in range(25):
        if k < 17:
            fs.append(f"U32.xor(e{k},even(l{k},h{k}))")
            fs.append(f"U32.xor(o{k},odd(l{k},h{k}))")
        else:
            fs += [f"e{k}", f"o{k}"]
    o.append("      T.St{" + ",".join(fs) + "}")
    o.append("")
    o.append("# The first four lanes as plain lanes, the rest zero: all the digest reads.")
    o.append("def squeeze(s: T.St) -> T.State:")
    o.append("  match s:")
    o.append("    case T.St{" + plus_fields() + "}:")
    lanes = []
    for k in range(4):
        e, od = (f"U32.not(e{k})", f"U32.not(o{k})") if k in COMPLEMENTED else (f"e{k}", f"o{k}")
        lanes.append(f"T.W{{low({e},{od}),high({e},{od})}}")
    lanes += ["T.W{0,0}"] * 21
    o.append("      T.S{" + ",".join(lanes) + "}")
    o.append("")
    return "\n".join(o)


# ---------------------------------------------------------------------------
# src/keccak.bend

PAD = """# Little-endian Keccak pad10*1, domain suffix 0x01.
def partial(w: U32, delta: Nat) -> U32:
  match delta:
    case 0n: 1
    case 1n: U32.or(U32.and(w,255),256)
    case 2n: U32.or(U32.and(w,65535),65536)
    case 3n: U32.or(U32.and(w,16777215),16777216)
    case _: w

def pad_choose(c: Cmp, w: U32, delta: Nat) -> U32:
  match c:
    case GT{}: 0
    case EQ{}: 1
    case LT{}: partial(w,delta)

def pad_word(w: U32, +pos: Nat, +remain: Nat) -> U32:
  pad_choose(Nat.cmp(pos,remain),w,Nat.sub(remain,pos))
"""

TAIL = """def digest(s: T.State) -> Array<U32>:
  match s:
    case T.S{T.W{l0,h0},T.W{l1,h1},T.W{l2,h2},T.W{l3,h3},a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24}:
      a = Array.new(U32,3n,0)
      a = Array.set(U32,a,0,l0)
      a = Array.set(U32,a,1,h0)
      a = Array.set(U32,a,2,l1)
      a = Array.set(U32,a,3,h1)
      a = Array.set(U32,a,4,l2)
      a = Array.set(U32,a,5,h2)
      a = Array.set(U32,a,6,l3)
      a = Array.set(U32,a,7,h3)
      a

def checked(+round_count: Nat,valid: Bool, a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:
  match valid:
    case False{}: None{}
    case True{}: Some{digest(L.squeeze(unchecked(round_count,a,length)))}

def sized(+round_count: Nat,+length: Nat, pair: Array<U32> & U32) -> Maybe<&1,Array<U32>>:
  (a,capacity) = pair
  checked(round_count,Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)

def keccak256_rounds(+round_count: Nat,a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:
  sized(round_count,length,Array.size(U32,a))


def keccak256(a: Array<U32>, length: Nat) -> Maybe<&1,Array<U32>>:
  keccak256_rounds(24n,a,length)
"""


def gen_keccak():
    o = [HEADER, "#",
         "# The Keccak-256 sponge over packed little-endian words: each block's 34",
         "# words are read in one unrolled chain, XORed into the interleaved state",
         "# (src/lane.bend) and permuted (src/permutation.bend); the last block is",
         "# padded word by word.",
         "import Base",
         "import ./types.bend as T",
         "import ./lane.bend as L",
         "import ./permutation.bend as P", ""]
    ws = lambda n: "".join(f", w{i}: U32" for i in range(n))
    wa = lambda n: "".join(f",w{i}" for i in range(n))
    o.append(f"def read33(+round_count: Nat,+index: U32, s: T.St{ws(33)}, pair: Array<U32> & U32) -> Array<U32> & T.St:")
    o.append("  (a,w33) = pair")
    o.append(f"  (a,P.steps(round_count,0n,L.mix(s{wa(34)})))")
    o.append("")
    for k in range(32, -1, -1):
        o.append(f"def read{k}(+round_count: Nat,+index: U32, s: T.St{ws(k)}, pair: Array<U32> & U32) -> Array<U32> & T.St:")
        o.append(f"  (a,w{k}) = pair")
        o.append(f"  read{k + 1}(round_count,index,s{wa(k + 1)},Array.get(U32,a,U32.add(index,{k + 1})))")
        o.append("")
    o.append("def absorb(+round_count: Nat,a: Array<U32>, +index: U32, s: T.St) -> Array<U32> & T.St:")
    o.append("  read0(round_count,index,s,Array.get(U32,a,index))")
    o.append("")
    o.append(PAD)
    padded = ",".join(f"pad_word(w{i},{4 * i}n,remain)" for i in range(33)) + ",U32.or(pad_word(w33,132n,remain),2147483648)"
    o.append(f"def pad33(+round_count: Nat,+remain: Nat, +index: U32, s: T.St{ws(33)}, pair: Array<U32> & U32) -> T.St:")
    o.append("  (a,w33) = pair")
    o.append(f"  P.steps(round_count,0n,L.mix(s,{padded}))")
    o.append("")
    for k in range(32, -1, -1):
        o.append(f"def pad{k}(+round_count: Nat,+remain: Nat, +index: U32, s: T.St{ws(k)}, pair: Array<U32> & U32) -> T.St:")
        o.append(f"  (a,w{k}) = pair")
        o.append(f"  pad{k + 1}(round_count,remain,index,s{wa(k + 1)},Array.get(U32,a,U32.add(index,{k + 1})))")
        o.append("")
    o += ["def finish(+round_count: Nat,a: Array<U32>, +index: U32, remain: Nat, s: T.St) -> T.St:",
          "  pad0(round_count,remain,index,s,Array.get(U32,a,index))", "",
          "def blocks(+round_count: Nat,n: Nat, +index: U32, remain: Nat, pair: Array<U32> & T.St) -> T.St:",
          "  match n pair:",
          "    case 0n Tuple{a,s}: finish(round_count,a,index,remain,s)",
          "    case 1n+p Tuple{a,s}: blocks(round_count,p,U32.add(index,34),remain,absorb(round_count,a,index,s))", "",
          "def unchecked(+round_count: Nat,a: Array<U32>, +length: Nat) -> T.St:",
          "  blocks(round_count,Nat.div(length,136n),0,Nat.mod(length,136n),(a,P.initial()))", "",
          TAIL]
    return "\n".join(o)


# ---------------------------------------------------------------------------
# spec/interleave.bend

def gen_spec():
    o = [HEADER, "#",
         "# The interleaved representation of a state (src/types.bend St): lane k is",
         "# held as its even bits and its odd bits, each packed into a U32 (bit j of",
         "# the lane is bit j/2 of the even or the odd word), complemented for the",
         "# lanes 1, 2, 8, 12, 17, 20. Pure bit shuffles over Base's Word.",
         "import Base",
         "import ../src/types.bend as T", ""]
    lo, hi = lwords("b")
    o.append("def even(x: T.Lane) -> U32:")
    o.append("  match x:")
    o.append(f"    case {lpat('b')}:")
    o.append("      " + uword([bshow(v) for v in ie_w(lo, hi)]))
    o.append("")
    o.append("def odd(x: T.Lane) -> U32:")
    o.append("  match x:")
    o.append(f"    case {lpat('b')}:")
    o.append("      " + uword([bshow(v) for v in io_w(lo, hi)]))
    o.append("")
    o.append("def interleave(s: T.State) -> T.St:")
    o.append("  match s:")
    o.append("    case T.S{" + ",".join(f"+a{k}" for k in range(25)) + "}:")
    fs = []
    for k in range(25):
        if k in COMPLEMENTED:
            fs += [f"U32.not(even(a{k}))", f"U32.not(odd(a{k}))"]
        else:
            fs += [f"even(a{k})", f"odd(a{k})"]
    o.append("      T.St{" + ",".join(fs) + "}")
    o.append("")
    return "\n".join(o)


# ---------------------------------------------------------------------------
# proofs/permutation.bend

def ccol(x):
    return f"X{{V{{{x}n}},X{{V{{{x + 5}n}},X{{V{{{x + 10}n}},X{{V{{{x + 15}n}},V{{{x + 20}n}}}}}}}}}}"


def eb(dest):
    src, r = B[dest]
    x = src % 5
    d = f"X{{{ccol((x - 1) % 5)},R{{1n,{ccol((x + 1) % 5)}}}}}"
    return f"R{{{r}n,X{{V{{{src}n}},{d}}}}}"


def mask_b(dest):
    src, _ = B[dest]
    x = src % 5
    col = lambda c: sum((c + 5 * y) in COMPLEMENTED for y in range(5)) % 2
    d = col((x - 1) % 5) ^ col((x + 1) % 5)
    return bool((src in COMPLEMENTED) ^ d)


def gen_proofs_perm():
    bl = Bools("bit")
    o = []
    I = "I"  # spec/interleave alias
    TF = lambda b: "True{}" if b else "False{}"

    # --- evaluators -------------------------------------------------------
    o.append("# Pairs (even, odd); mx complements both halves when m holds.")
    o.append("def il(+x: T.Lane) -> U32 & U32:")
    o.append("  (I.even(x),I.odd(x))")
    o.append("")
    o.append("def mx(p: U32 & U32, m: Bool) -> U32 & U32:")
    o.append("  match p m:")
    o.append("    case Tuple{e,o} False{}: (e,o)")
    o.append("    case Tuple{e,o} True{}: (U32.not(e),U32.not(o))")
    o.append("")
    o.append("def pxor(p: U32 & U32, q: U32 & U32) -> U32 & U32:")
    o.append("  match p q:")
    o.append("    case Tuple{pe,po} Tuple{qe,qo}: (U32.xor(pe,qe),U32.xor(po,qo))")
    o.append("")
    o.append("# Whether lane n is held complemented.")
    o.append("def cm(n: Nat) -> Bool:")
    o.append("  match n:")
    for k in sorted(COMPLEMENTED):
        o.append(f"    case {k}n: True{{}}")
    o.append("    case _: False{}")
    o.append("")
    o.append("def rol(n: Nat, x: T.Lane) -> T.Lane:")
    o.append("  match n:")
    for r in ROTS:
        o.append(f"    case {r}n: F.rotate(x,{r}n)")
    o.append("    case _: x")
    o.append("")
    o.append("def irot(n: Nat, p: U32 & U32) -> U32 & U32:")
    o.append("  match n p:")
    for r in ROTS:
        if r % 2 == 0:
            e, od = rot("e", r // 2), rot("o", r // 2)
        else:
            e, od = rot("o", r // 2 + 1), rot("e", r // 2)
        o.append(f"    case {r}n Tuple{{+e,+o}}: ({e},{od})")
    o.append("    case _ p: p")
    o.append("")
    o.append("# Theta/rho expressions: input lanes, the round constant, XOR, rotation.")
    o.append("type Ex is Data:")
    o.append("  V{n: Nat}")
    o.append("  C{}")
    o.append("  X{a: Ex, b: Ex}")
    o.append("  R{n: Nat, a: Ex}")
    o.append("")
    o.append("def sv(+s: T.State, +rc: T.Lane, e: Ex) -> T.Lane:")
    o.append("  match e:")
    o.append("    case V{n}: F.at(s,n)")
    o.append("    case C{}: rc")
    o.append("    case X{a,b}: F.xor(sv(s,rc,a),sv(s,rc,b))")
    o.append("    case R{n,a}: rol(n,sv(s,rc,a))")
    o.append("")
    o.append("def ge(+t: T.St, n: Nat) -> U32 & U32:")
    o.append("  match t n:")
    for k in range(25):
        o.append(f"    case T.St{{{st_fields()}}} {k}n: (e{k},o{k})")
    o.append("    case _ _: (0,0)")
    o.append("")
    o.append("def fv(+t: T.St, +rce: U32, +rco: U32, e: Ex) -> U32 & U32:")
    o.append("  match e:")
    o.append("    case V{n}: ge(t,n)")
    o.append("    case C{}: (rce,rco)")
    o.append("    case X{a,b}: pxor(fv(t,rce,rco,a),fv(t,rce,rco,b))")
    o.append("    case R{n,a}: irot(n,fv(t,rce,rco,a))")
    o.append("")
    o.append("def mk(e: Ex) -> Bool:")
    o.append("  match e:")
    o.append("    case V{n}: cm(n)")
    o.append("    case C{}: False{}")
    o.append("    case X{a,b}: Bool.xor(mk(a),mk(b))")
    o.append("    case R{n,a}: mk(a)")
    o.append("")
    for k in range(25):
        nx, op, ny, nz = CHI[k]
        o.append(f"def vchi{k}(p: U32 & U32, q: U32 & U32, r: U32 & U32) -> U32 & U32:")
        o.append("  match p q r:")
        o.append("    case Tuple{pe,po} Tuple{qe,qo} Tuple{re,ro}:")
        o.append(f"      ({chi_k(k, 'pe', 'qe', 're')},{chi_k(k, 'po', 'qo', 'ro')})")
        o.append("")
    for dest in range(25):
        o.append(f"def b{dest}() -> Ex:")
        o.append(f"  {eb(dest)}")
        o.append("")

    # --- generic congruences ----------------------------------------------
    o += ["law pair_eq:",
          "  for -a: U32", "  for -b: U32", "  for -c: U32", "  for -d: U32",
          "  for e1: {a == c : U32}", "  for e2: {b == d : U32}",
          "  {(a,b) == (c,d) : U32 & U32}", "",
          "def pair_eq(a,b,c,d,e1,e2):",
          "  %e1 : {(a,b) == (_,d) : U32 & U32}",
          "  %e2 : {(a,b) == (a,_) : U32 & U32}",
          "  {==}", ""]

    def cong_lemma(name, fn, n, ty="U32 & U32", rty="U32 & U32"):
        L = [f"law {name}:"]
        for i in range(n):
            L += [f"  for -x{i}: {ty}", f"  for -y{i}: {ty}"]
        for i in range(n):
            L.append(f"  for e{i}: {{x{i} == y{i} : {ty}}}")
        xs = ",".join(f"x{i}" for i in range(n))
        ys = ",".join(f"y{i}" for i in range(n))
        L.append(f"  {{{fn}({xs}) == {fn}({ys}) : {rty}}}")
        L.append("")
        args = ",".join(f"x{i},y{i}" for i in range(n)) + "," + ",".join(f"e{i}" for i in range(n))
        L.append(f"def {name}({args}):")
        for i in range(n):
            cur = [f"x{j}" for j in range(i)] + ["_"] + [f"y{j}" for j in range(i + 1, n)]
            L.append(f"  %e{i} : {{{fn}({xs}) == {fn}({','.join(cur)}) : {rty}}}")
        L.append("  {==}")
        L.append("")
        return L

    o += cong_lemma("pxor_cong", "pxor", 2)
    for k in range(25):
        o += cong_lemma(f"vchi{k}_cong", f"vchi{k}", 3)
    o += ["law irot_cong:", "  for n: Nat", "  for -x: U32 & U32", "  for -y: U32 & U32",
          "  for e: {x == y : U32 & U32}", "  {irot(n,x) == irot(n,y) : U32 & U32}", "",
          "def irot_cong(n,x,y,e):", "  %e : {irot(n,x) == irot(n,_) : U32 & U32}", "  {==}", ""]
    # St from 25 pairs
    o.append("def st(" + ",".join(f"p{k}: U32 & U32" for k in range(25)) + ") -> T.St:")
    for k in range(25):
        o.append(f"  (e{k},o{k}) = p{k}")
    o.append(f"  T.St{{{st_fields()}}}")
    o.append("")
    o += cong_lemma("st_cong", "st", 25, rty="T.St")

    # --- lane lemmas --------------------------------------------------------
    xl, xh = lwords("x")
    yl, yh = lwords("y")
    zl, zh = lwords("z")
    X = ("x", xl, xh)
    Y = ("y", yl, yh)

    def pair_proof(lhs_pair, rhs_pair, le, lo_, re_, ro):
        """{lhs_pair == rhs_pair} from symbolic components."""
        fe = f"Pair.fst(U32,U32,{lhs_pair})"
        fo = f"Pair.snd(U32,U32,{lhs_pair})"
        ge_ = f"Pair.fst(U32,U32,{rhs_pair})"
        go_ = f"Pair.snd(U32,U32,{rhs_pair})"
        return f"pair_eq({fe},{fo},{ge_},{go_},{bl.ext(fe, ge_, le, re_)},{bl.ext(fo, go_, lo_, ro)})"

    # xor lemma
    o += ["law xor_il:", "  for +x: T.Lane", "  for +y: T.Lane", "  for ma: Bool", "  for mb: Bool",
          "  {pxor(mx(il(x),ma),mx(il(y),mb)) == mx(il(F.xor(x,y)),Bool.xor(ma,mb)) : U32 & U32}", "",
          "def xor_il(x,y,ma,mb):", "  match x y ma mb:"]
    for ma in (False, True):
        for mb in (False, True):
            ex, ox = ie_w(xl, xh), io_w(xl, xh)
            ey, oy = ie_w(yl, yh), io_w(yl, yh)
            le = w_xor(mx(ex, ma), mx(ey, mb))
            lo_ = w_xor(mx(ox, ma), mx(oy, mb))
            sl, sh = w_xor(xl, yl), w_xor(xh, yh)
            re_ = mx(ie_w(sl, sh), ma != mb)
            ro = mx(io_w(sl, sh), ma != mb)
            lhs = f"pxor(mx(il(x),{TF(ma)}),mx(il(y),{TF(mb)}))"
            rhs = f"mx(il(F.xor(x,y)),{TF(ma != mb)})"
            o.append(f"    case {lpat('x')} {lpat('y')} {TF(ma)} {TF(mb)}:")
            o.append("      " + pair_proof(lhs, rhs, le, lo_, re_, ro))
    o.append("")

    # rotation lemmas, one per amount
    for r in ROTS:
        o += [f"law rot{r}_il:", "  for +x: T.Lane", "  for m: Bool",
              f"  {{irot({r}n,mx(il(x),m)) == mx(il(rol({r}n,x)),m) : U32 & U32}}", "",
              f"def rot{r}_il(x,m):", "  match x m:"]
        for m in (False, True):
            ex, ox = mx(ie_w(xl, xh), m), mx(io_w(xl, xh), m)
            le, lo_ = impl_rot(ex, ox, r)
            rl, rh = spec_rol(xl, xh, r)
            re_, ro = mx(ie_w(rl, rh), m), mx(io_w(rl, rh), m)
            lhs = f"irot({r}n,mx(il(x),{TF(m)}))"
            rhs = f"mx(il(rol({r}n,x)),{TF(m)})"
            o.append(f"    case {lpat('x')} {TF(m)}:")
            o.append("      " + pair_proof(lhs, rhs, le, lo_, re_, ro))
        o.append("")
    o += ["law rot_il:", "  for n: Nat", "  for +x: T.Lane", "  for m: Bool",
          "  {irot(n,mx(il(x),m)) == mx(il(rol(n,x)),m) : U32 & U32}", "",
          "def rot_il(n,x,m):", "  match n m:"]
    for r in range(64):
        if r in ROTS:
            o.append(f"    case {r}n m: rot{r}_il(x,m)")
        else:
            o.append(f"    case {r}n False{{}}: {{==}}")
            o.append(f"    case {r}n True{{}}: {{==}}")
    o.append("    case 64n+k False{}: {==}")
    o.append("    case 64n+k True{}: {==}")
    o.append("")

    # chi lemmas, one per output lane, with that lane's input masks
    for k in range(25):
        a, b, c = row3(k)
        ma, mb, mc = mask_b(a), mask_b(b), mask_b(c)
        mo = k in COMPLEMENTED
        ex, ox = ie_w(xl, xh), io_w(xl, xh)
        ey, oy = ie_w(yl, yh), io_w(yl, yh)
        ez, oz = ie_w(zl, zh), io_w(zl, zh)
        le = impl_chi(k, mx(ex, ma), mx(ey, mb), mx(ez, mc))
        lo_ = impl_chi(k, mx(ox, ma), mx(oy, mb), mx(oz, mc))
        cl, ch = spec_chi(xl, yl, zl), spec_chi(xh, yh, zh)
        re_, ro = mx(ie_w(cl, ch), mo), mx(io_w(cl, ch), mo)
        lhs = f"vchi{k}(mx(il(x),{TF(ma)}),mx(il(y),{TF(mb)}),mx(il(z),{TF(mc)}))"
        rhs = f"mx(il(F.chi(x,y,z)),{TF(mo)})"
        o += [f"law chi{k}_il:", "  for +x: T.Lane", "  for +y: T.Lane", "  for +z: T.Lane",
              f"  {{{lhs} == {rhs} : U32 & U32}}", "",
              f"def chi{k}_il(x,y,z):", "  match x y z:",
              f"    case {lpat('x')} {lpat('y')} {lpat('z')}:",
              "      " + pair_proof(lhs, rhs, le, lo_, re_, ro), ""]

    # --- expression refinement ----------------------------------------------
    o.append("law var_il:")
    o.append("  for +s: T.State")
    o.append("  for +n: Nat")
    o.append("  {ge(I.interleave(s),n) == mx(il(F.at(s,n)),cm(n)) : U32 & U32}")
    o.append("")
    o.append("def var_il(s,n):")
    o.append("  match s n:")
    sp = "T.S{" + ",".join(f"a{k}" for k in range(25)) + "}"
    for k in range(25):
        o.append(f"    case {sp} {k}n: {{==}}")
    o.append(f"    case {sp} 25n+k: {{==}}")
    o.append("")
    o += ["law ex_il:", "  for +s: T.State", "  for +rc: T.Lane", "  for e: Ex",
          "  {fv(I.interleave(s),I.even(rc),I.odd(rc),e) == mx(il(sv(s,rc,e)),mk(e)) : U32 & U32}", "",
          "def ex_il(s,rc,e):",
          "  match e:",
          "    case V{n}: var_il(s,n)",
          "    case C{}: {==}",
          "    case X{+a,+b}:",
          "      Equal.trans(U32 & U32,",
          "        pxor(fv(I.interleave(s),I.even(rc),I.odd(rc),a),fv(I.interleave(s),I.even(rc),I.odd(rc),b)),",
          "        pxor(mx(il(sv(s,rc,a)),mk(a)),mx(il(sv(s,rc,b)),mk(b))),",
          "        mx(il(F.xor(sv(s,rc,a),sv(s,rc,b))),Bool.xor(mk(a),mk(b))),",
          "        pxor_cong(fv(I.interleave(s),I.even(rc),I.odd(rc),a),mx(il(sv(s,rc,a)),mk(a)),fv(I.interleave(s),I.even(rc),I.odd(rc),b),mx(il(sv(s,rc,b)),mk(b)),ex_il(s,rc,a),ex_il(s,rc,b)),",
          "        xor_il(sv(s,rc,a),sv(s,rc,b),mk(a),mk(b)))",
          "    case R{+n,+a}:",
          "      Equal.trans(U32 & U32,",
          "        irot(n,fv(I.interleave(s),I.even(rc),I.odd(rc),a)),",
          "        irot(n,mx(il(sv(s,rc,a)),mk(a))),",
          "        mx(il(rol(n,sv(s,rc,a))),mk(a)),",
          "        irot_cong(n,fv(I.interleave(s),I.even(rc),I.odd(rc),a),mx(il(sv(s,rc,a)),mk(a)),ex_il(s,rc,a)),",
          "        rot_il(n,sv(s,rc,a),mk(a)))", ""]

    # --- lanes and the round -------------------------------------------------
    FV = lambda d: f"fv(I.interleave(s),I.even(rc),I.odd(rc),b{d}())"
    SV = lambda d: f"sv(s,rc,b{d}())"
    MK = lambda d: f"mx(il(sv(s,rc,b{d}())),mk(b{d}()))"
    lane_x, lane_y = [], []
    for k in range(25):
        a, b, c = row3(k)
        mo = k in COMPLEMENTED
        lhs = f"vchi{k}({FV(a)},{FV(b)},{FV(c)})"
        rhs = f"mx(il(F.chi({SV(a)},{SV(b)},{SV(c)})),{TF(mo)})"
        mid = f"vchi{k}({MK(a)},{MK(b)},{MK(c)})"
        o += [f"law lane{k}:", "  for +s: T.State", "  for +rc: T.Lane",
              f"  {{{lhs} == {rhs} : U32 & U32}}", "",
              f"def lane{k}(s,rc):",
              f"  Equal.trans(U32 & U32,{lhs},{mid},{rhs},",
              f"    vchi{k}_cong({FV(a)},{MK(a)},{FV(b)},{MK(b)},{FV(c)},{MK(c)},ex_il(s,rc,b{a}()),ex_il(s,rc,b{b}()),ex_il(s,rc,b{c}())),",
              f"    chi{k}_il({SV(a)},{SV(b)},{SV(c)}))", ""]
        if k == 0:
            chi0 = f"F.chi({SV(a)},{SV(b)},{SV(c)})"
            l0 = f"pxor({lhs},(I.even(rc),I.odd(rc)))"
            r0 = f"il(F.xor({chi0},rc))"
            m0 = f"pxor(il({chi0}),il(rc))"
            o += ["law lane0rc:", "  for +s: T.State", "  for +rc: T.Lane",
                  f"  {{{l0} == {r0} : U32 & U32}}", "",
                  "def lane0rc(s,rc):",
                  f"  Equal.trans(U32 & U32,{l0},{m0},{r0},",
                  f"    pxor_cong({lhs},il({chi0}),(I.even(rc),I.odd(rc)),il(rc),lane0(s,rc),{{==}}),",
                  f"    xor_il({chi0},rc,False{{}},False{{}}))", ""]
            lane_x.append(l0)
            lane_y.append(r0)
        else:
            lane_x.append(lhs)
            lane_y.append(rhs)
    o += ["law round_il:", "  for +s: T.State", "  for +rc: T.Lane",
          "  {P.round(I.interleave(s),I.even(rc),I.odd(rc)) == I.interleave(F.round(s,rc)) : T.St}", "",
          "def round_il(s,rc):",
          "  match s:",
          "    case T.S{" + ",".join(f"+a{k}" for k in range(25)) + "}:",
          "      st_cong(" + ",".join(f"{lane_x[k]},{lane_y[k]}" for k in range(25)) + ","
          + ",".join(("lane0rc(s,rc)" if k == 0 else f"lane{k}(s,rc)") for k in range(25)) + ")", ""]

    # --- constants and rounds --------------------------------------------------
    o += ["law rce_il:", "  for +i: Nat", "  {P.rce(i) == I.even(F.constant(i)) : U32}", "",
          "def rce_il(i):", "  match i:"]
    o += [f"    case {i}n: {{==}}" for i in range(24)] + ["    case 24n+k: {==}", ""]
    o += ["law rco_il:", "  for +i: Nat", "  {P.rco(i) == I.odd(F.constant(i)) : U32}", "",
          "def rco_il(i):", "  match i:"]
    o += [f"    case {i}n: {{==}}" for i in range(24)] + ["    case 24n+k: {==}", ""]
    o += ["law step_il:", "  for +i: Nat", "  for +s: T.State",
          "  {P.round(I.interleave(s),P.rce(i),P.rco(i)) == I.interleave(F.round(s,F.constant(i))) : T.St}", "",
          "def step_il(i,s):",
          "  %Equal.sym(U32,P.rce(i),I.even(F.constant(i)),rce_il(i)) : {P.round(I.interleave(s),_,P.rco(i)) == I.interleave(F.round(s,F.constant(i))) : T.St}",
          "  %Equal.sym(U32,P.rco(i),I.odd(F.constant(i)),rco_il(i)) : {P.round(I.interleave(s),I.even(F.constant(i)),_) == I.interleave(F.round(s,F.constant(i))) : T.St}",
          "  round_il(s,F.constant(i))", ""]
    o += ["law steps_pair:", "  for +n: Nat", "  for +i: Nat", "  for +t: T.St",
          "  {P.steps(2n+n,i,t) == P.steps(n,2n+i,P.round(P.round(t,P.rce(i),P.rco(i)),P.rce(1n+i),P.rco(1n+i))) : T.St}", "",
          "def steps_pair(n,i,t):", "  match t:",
          f"    case T.St{{{st_fields()}}}: {{==}}", ""]
    two_f = "P.round(P.round(I.interleave(s),P.rce(i),P.rco(i)),P.rce(1n+i),P.rco(1n+i))"
    two_p = "F.round(F.round(s,F.constant(i)),F.constant(1n+i))"
    mid_f = "P.round(I.interleave(F.round(s,F.constant(i))),P.rce(1n+i),P.rco(1n+i))"
    o += ["law two_il:", "  for +i: Nat", "  for +s: T.State",
          f"  {{{two_f} == I.interleave({two_p}) : T.St}}", "",
          "def two_il(i,s):",
          f"  Equal.trans(T.St,{two_f},{mid_f},I.interleave({two_p}),",
          "    Equal.cong(T.St,T.St,t => P.round(t,P.rce(1n+i),P.rco(1n+i)),P.round(I.interleave(s),P.rce(i),P.rco(i)),I.interleave(F.round(s,F.constant(i))),step_il(i,s)),",
          "    step_il(1n+i,F.round(s,F.constant(i))))", ""]
    o += ["law steps_spec:", "  for +n: Nat", "  for +i: Nat", "  for +s: T.State",
          "  {P.steps(n,i,I.interleave(s)) == I.interleave(F.rounds(n,i,s)) : T.St}", "",
          "def steps_spec(n,i,s):",
          "  match n:",
          "    case 0n: {==}",
          "    case 1n: step_il(i,s)",
          "    case 2n+p:",
          "      Equal.trans(T.St,",
          "        P.steps(2n+p,i,I.interleave(s)),",
          f"        P.steps(p,2n+i,{two_f}),",
          "        I.interleave(F.rounds(2n+p,i,s)),",
          "        steps_pair(p,i,I.interleave(s)),",
          "        Equal.trans(T.St,",
          f"          P.steps(p,2n+i,{two_f}),",
          f"          P.steps(p,2n+i,I.interleave({two_p})),",
          "          I.interleave(F.rounds(2n+p,i,s)),",
          f"          Equal.cong(T.St,T.St,t => P.steps(p,2n+i,t),{two_f},I.interleave({two_p}),two_il(i,s)),",
          f"          steps_spec(p,2n+i,{two_p})))", ""]

    # --- word conversions --------------------------------------------------------
    xw = wvar("x")
    perms = []
    for k, m in STAGES:
        sw = stage_w(xw, k, m)
        perm = stage_perm(k, m)
        perms.append(perm)
        target = [xw[perm[i]] for i in range(32)]
        o += [f"def pswap{k}(x: U32) -> U32:", "  match x:",
              f"    case {upat('x')}: {uword([bshow(v) for v in target])}", ""]
        o += [f"law swap{k}_perm:", "  for +x: U32", f"  {{L.swap{k}(x) == pswap{k}(x) : U32}}", "",
              f"def swap{k}_perm(x):", "  match x:",
              f"    case {upat('x')}:",
              "      " + bl.ext(f"L.swap{k}(x)", f"pswap{k}(x)", sw, target), ""]
    unz_p = compose(*perms)
    zip_p = compose(*reversed(perms))
    for name, p in (("punz", unz_p), ("pzip", zip_p)):
        o += [f"def {name}(x: U32) -> U32:", "  match x:",
              f"    case {upat('x')}: {uword([bshow(xw[p[i]]) for i in range(32)])}", ""]
    # zip by stages
    def nest(fs, x):
        for f in fs:
            x = f"{f}({x})"
        return x
    order = [8, 4, 2, 1]
    cur = [f"L.swap{k}" for k in order]
    terms = [nest(cur, "x")]
    for j in range(4):
        cur = cur[:j] + [f"pswap{order[j]}"] + cur[j + 1:]
        terms.append(nest(cur, "x"))
    o += ["law pzip_parts:", "  for +x: U32", f"  {{{terms[4]} == pzip(x) : U32}}", "",
          "def pzip_parts(x):", "  match x:", f"    case {upat('x')}: {{==}}", ""]
    proof = "pzip_parts(x)"
    for j in range(3, -1, -1):
        inner = nest([f"pswap{order[i]}" for i in range(j)], "x")
        lam = nest([f"L.swap{order[i]}" for i in range(j + 1, 4)], "v")
        step = (f"Equal.cong(U32,U32,v => {lam},L.swap{order[j]}({inner}),pswap{order[j]}({inner}),"
                f"swap{order[j]}_perm({inner}))")
        proof = f"Equal.trans(U32,{terms[j]},{terms[j + 1]},pzip(x),{step},{proof})"
    o += ["law zip_perm:", "  for +x: U32", "  {L.zip(x) == pzip(x) : U32}", "",
          "def zip_perm(x):", f"  {proof}", ""]
    # unz by tables: each byte's table entry is that byte's bits, placed
    for k in range(4):
        bits = ["False{}"] * 32
        for jj in range(4):
            bits[4 * k + jj] = f"x{8 * k + 2 * jj}"
            bits[16 + 4 * k + jj] = f"x{8 * k + 2 * jj + 1}"
        o += [f"def pbyte{k}(x: U32) -> U32:", "  match x:", f"    case {upat('x')}: {uword(bits)}", ""]
        bv = [f"x{8 * k + jj}" for jj in range(8)]
        o += [f"law byte{k}_perm:", "  for +x: U32", f"  {{L.ub{k}(U32.to_nat({BYTE_SEL[k]})) == pbyte{k}(x) : U32}}", "",
              f"def byte{k}_perm(x):", "  match x:"]
        for vals in itertools.product(["False{}", "True{}"], repeat=8):
            bits = [f"x{i}" for i in range(32)]
            for jj in range(8):
                bits[8 * k + jj] = vals[jj]
            o.append(f"    case {uword(bits)}: {{==}}")
        o.append("")
    sel = [f"L.ub{k}(U32.to_nat({BYTE_SEL[k]}))" for k in range(4)]
    pb = [f"pbyte{k}(x)" for k in range(4)]
    comb = lambda a: f"U32.or(U32.or({a[0]},{a[1]}),U32.or({a[2]},{a[3]}))"
    o += ["law or4_cong:"] + [f"  for -a{k}: U32\n  for -b{k}: U32" for k in range(4)] + \
         [f"  for e{k}: {{a{k} == b{k} : U32}}" for k in range(4)] + \
         [f"  {{{comb(['a0','a1','a2','a3'])} == {comb(['b0','b1','b2','b3'])} : U32}}", "",
          "def or4_cong(a0,b0,a1,b1,a2,b2,a3,b3,e0,e1,e2,e3):"]
    for k in range(4):
        cur = [f"a{m}" for m in range(k)] + ["_"] + [f"b{m}" for m in range(k + 1, 4)]
        o.append(f"  %e{k} : {{{comb(['a0','a1','a2','a3'])} == {comb(cur)} : U32}}")
    o += ["  {==}", ""]
    xw = wvar("x")
    pbw = []
    for k in range(4):
        w = [F] * 32
        for jj in range(4):
            w[4 * k + jj] = xw[8 * k + 2 * jj]
            w[16 + 4 * k + jj] = xw[8 * k + 2 * jj + 1]
        pbw.append(w)
    combw = w_or(w_or(pbw[0], pbw[1]), w_or(pbw[2], pbw[3]))
    target = [xw[unz_p[i]] for i in range(32)]
    o += ["law punz_parts:", "  for +x: U32", f"  {{{comb(pb)} == punz(x) : U32}}", "",
          "def punz_parts(x):", "  match x:", f"    case {upat('x')}:",
          "      " + bl.ext(comb(pb), "punz(x)", combw, target), ""]
    o += ["law unz_perm:", "  for +x: U32", "  {L.unz(x) == punz(x) : U32}", "",
          "def unz_perm(x):",
          f"  Equal.trans(U32,{comb(sel)},{comb(pb)},punz(x),",
          f"    or4_cong({','.join(f'{sel[k]},{pb[k]}' for k in range(4))},{','.join(f'byte{k}_perm(x)' for k in range(4))}),",
          "    punz_parts(x))", ""]
    # even/odd of a word pair
    ul, uh = [xw[unz_p[i]] for i in range(32)], None
    lo_w, hi_w = wvar("x"), wvar("y")
    ul = [lo_w[unz_p[i]] for i in range(32)]
    uh = [hi_w[unz_p[i]] for i in range(32)]
    ev = w_or(w_and(lit(65535), ul), w_shln(uh, 16))
    od = w_or(w_shrn(ul, 16), w_and(lit(4294901760), uh))
    o += ["law split_il:", "  for +x: U32", "  for +y: U32",
          "  {(L.even(punz(x),punz(y)),L.odd(punz(x),punz(y))) == il(T.W{x,y}) : U32 & U32}", "",
          "def split_il(x,y):", "  match x y:",
          f"    case {upat('x')} {upat('y')}:",
          "      " + pair_proof("(L.even(punz(x),punz(y)),L.odd(punz(x),punz(y)))", "il(T.W{x,y})",
                                ev, od, ie_w(lo_w, hi_w), io_w(lo_w, hi_w)), ""]
    o += ["law words_il:", "  for +x: U32", "  for +y: U32",
          "  {(L.even(L.unz(x),L.unz(y)),L.odd(L.unz(x),L.unz(y))) == il(T.W{x,y}) : U32 & U32}", "",
          "def words_il(x,y):",
          "  %Equal.sym(U32,L.unz(x),punz(x),unz_perm(x)) : {(L.even(_,L.unz(y)),L.odd(_,L.unz(y))) == il(T.W{x,y}) : U32 & U32}",
          "  %Equal.sym(U32,L.unz(y),punz(y),unz_perm(y)) : {(L.even(punz(x),_),L.odd(punz(x),_)) == il(T.W{x,y}) : U32 & U32}",
          "  split_il(x,y)", ""]
    # low/high of an interleaved lane, possibly complemented twice
    for m in (False, True):
        sfx = "c" if m else ""
        ex, ox = ie_w(lo_w, hi_w), io_w(lo_w, hi_w)
        if m:
            ex, ox = w_not(w_not(ex)), w_not(w_not(ox))
            eT = "U32.not(U32.not(I.even(T.W{x,y})))"
            oT = "U32.not(U32.not(I.odd(T.W{x,y})))"
        else:
            eT, oT = "I.even(T.W{x,y})", "I.odd(T.W{x,y})"
        lo_in = w_or(w_and(lit(65535), ex), w_shln(ox, 16))
        hi_in = w_or(w_shrn(ex, 16), w_and(lit(4294901760), ox))
        lo_out = [lo_in[zip_p[i]] for i in range(32)]
        hi_out = [hi_in[zip_p[i]] for i in range(32)]
        for part, arg, out, target in (("low", f"U32.or(U32.and(65535,{eT}),U32.shln({oT},16n))", lo_out, lo_w),
                                       ("high", f"U32.or(U32.shrn({eT},16n),U32.and(4294901760,{oT}))", hi_out, hi_w)):
            tgt = "x" if part == "low" else "y"
            o += [f"law {part}{sfx}_p:", "  for +x: U32", "  for +y: U32",
                  f"  {{pzip({arg}) == {tgt} : U32}}", "",
                  f"def {part}{sfx}_p(x,y):", "  match x y:",
                  f"    case {upat('x')} {upat('y')}:",
                  "      " + bl.ext(f"pzip({arg})", tgt, out, target), ""]
            o += [f"law {part}{sfx}_il:", "  for +x: U32", "  for +y: U32",
                  f"  {{L.{part}({eT},{oT}) == {tgt} : U32}}", "",
                  f"def {part}{sfx}_il(x,y):",
                  f"  Equal.trans(U32,L.{part}({eT},{oT}),pzip({arg}),{tgt},zip_perm({arg}),{part}{sfx}_p(x,y))", ""]
    E = "L.even(L.unz(x),L.unz(y))"
    Od = "L.odd(L.unz(x),L.unz(y))"
    W = "T.W{x,y}"
    rt = ["law roundtrip_il:", "  for +x: U32", "  for +y: U32",
          f"  {{T.W{{L.low({E},{Od}),L.high({E},{Od})}} == T.W{{x,y}} : T.Lane}}", "",
          "def roundtrip_il(x,y):",
          f"  Equal.trans(T.Lane,T.W{{L.low({E},{Od}),L.high({E},{Od})}},T.W{{L.low(I.even({W}),I.odd({W})),L.high(I.even({W}),I.odd({W}))}},T.W{{x,y}},",
          f"    Equal.cong(U32 & U32,T.Lane,p => T.W{{L.low(Pair.fst(U32,U32,p),Pair.snd(U32,U32,p)),L.high(Pair.fst(U32,U32,p),Pair.snd(U32,U32,p))}},({E},{Od}),il({W}),words_il(x,y)),",
          f"    lanes_il(x,y))", ""]
    o += ["law lanes_il:", "  for +x: U32", "  for +y: U32",
          f"  {{T.W{{L.low(I.even({W}),I.odd({W})),L.high(I.even({W}),I.odd({W}))}} == T.W{{x,y}} : T.Lane}}", "",
          "def lanes_il(x,y):",
          f"  %Equal.sym(U32,L.low(I.even({W}),I.odd({W})),x,low_il(x,y)) : {{T.W{{_,L.high(I.even({W}),I.odd({W}))}} == T.W{{x,y}} : T.Lane}}",
          f"  %Equal.sym(U32,L.high(I.even({W}),I.odd({W})),y,high_il(x,y)) : {{T.W{{x,_}} == T.W{{x,y}} : T.Lane}}",
          "  {==}", ""]
    o += rt
    # enter/leave: whole-state conversions, and the permutation on plain lanes
    o += ["law lanesc_il:", "  for +x: U32", "  for +y: U32",
          f"  {{T.W{{L.low(U32.not(U32.not(I.even({W}))),U32.not(U32.not(I.odd({W})))),L.high(U32.not(U32.not(I.even({W}))),U32.not(U32.not(I.odd({W}))))}} == T.W{{x,y}} : T.Lane}}", "",
          "def lanesc_il(x,y):",
          f"  %Equal.sym(U32,L.low(U32.not(U32.not(I.even({W}))),U32.not(U32.not(I.odd({W})))),x,lowc_il(x,y)) : {{T.W{{_,L.high(U32.not(U32.not(I.even({W}))),U32.not(U32.not(I.odd({W}))))}} == T.W{{x,y}} : T.Lane}}",
          f"  %Equal.sym(U32,L.high(U32.not(U32.not(I.even({W}))),U32.not(U32.not(I.odd({W})))),y,highc_il(x,y)) : {{T.W{{x,_}} == T.W{{x,y}} : T.Lane}}",
          "  {==}", ""]
    o.append("def ts(" + ",".join(f"l{k}: T.Lane" for k in range(25)) + ") -> T.State:")
    o.append("  T.S{" + ",".join(f"l{k}" for k in range(25)) + "}")
    o.append("")
    o += cong_lemma("ts_cong", "ts", 25, ty="T.Lane", rty="T.State")
    xs_, ys_, ps_ = [], [], []
    for k in range(25):
        m = TF(k in COMPLEMENTED)
        wk = f"T.W{{x{k},y{k}}}"
        words = f"(L.even(L.unz(x{k}),L.unz(y{k})),L.odd(L.unz(x{k}),L.unz(y{k})))"
        xs_.append(f"mx({words},{m})")
        ys_.append(f"mx(il({wk}),{m})")
        ps_.append(f"Equal.cong(U32 & U32,U32 & U32,p => mx(p,{m}),{words},il({wk}),words_il(x{k},y{k}))")
    pat = "T.S{" + ",".join(f"T.W{{+x{k},+y{k}}}" for k in range(25)) + "}"
    o += ["law enter_il:", "  for +s: T.State", "  {L.enter(s) == I.interleave(s) : T.St}", "",
          "def enter_il(s):", "  match s:", f"    case {pat}:",
          "      st_cong(" + ",".join(f"{xs_[k]},{ys_[k]}" for k in range(25)) + "," + ",".join(ps_) + ")", ""]
    xs_, ys_, ps_ = [], [], []
    for k in range(25):
        wk = f"T.W{{x{k},y{k}}}"
        if k in COMPLEMENTED:
            e, od = f"U32.not(U32.not(I.even({wk})))", f"U32.not(U32.not(I.odd({wk})))"
            pf = f"lanesc_il(x{k},y{k})"
        else:
            e, od = f"I.even({wk})", f"I.odd({wk})"
            pf = f"lanes_il(x{k},y{k})"
        xs_.append(f"T.W{{L.low({e},{od}),L.high({e},{od})}}")
        ys_.append(wk)
        ps_.append(pf)
    o += ["law leave_il:", "  for +s: T.State", "  {L.leave(I.interleave(s)) == s : T.State}", "",
          "def leave_il(s):", "  match s:", f"    case {pat}:",
          "      ts_cong(" + ",".join(f"{xs_[k]},{ys_[k]}" for k in range(25)) + "," + ",".join(ps_) + ")", ""]
    o += ["law rounds_correct:", "  for +n: Nat", "  for +i: Nat", "  for +s: T.State",
          "  {P.rounds(n,i,s) == S.rounds(n,i,s) : T.State}", "",
          "def rounds_correct(n,i,s):",
          "  Equal.trans(T.State,L.leave(P.steps(n,i,L.enter(s))),L.leave(P.steps(n,i,I.interleave(s))),F.rounds(n,i,s),",
          "    Equal.cong(T.St,T.State,t => L.leave(P.steps(n,i,t)),L.enter(s),I.interleave(s),enter_il(s)),",
          "    Equal.trans(T.State,L.leave(P.steps(n,i,I.interleave(s))),L.leave(I.interleave(F.rounds(n,i,s))),F.rounds(n,i,s),",
          "      Equal.cong(T.St,T.State,t => L.leave(t),P.steps(n,i,I.interleave(s)),I.interleave(F.rounds(n,i,s)),steps_spec(n,i,s)),",
          "      leave_il(F.rounds(n,i,s))))", ""]
    return bl.out + o




def gen_proofs_perm_file():
    body = gen_proofs_perm()
    head = [HEADER, "#",
            "# The permutation (src/permutation.bend) against the specification",
            "# (spec/permutation.bend), through the interleaved representation of",
            "# spec/interleave.bend, and the word conversions of src/lane.bend against",
            "# that representation. Each bit-level step is an ext32 over Bool lemmas",
            "# (bitN) proven by cases; a round is assembled from per-lane lemmas over a",
            "# small expression language (Ex) evaluated on both representations.",
            "import Base",
            "import ../src/types.bend as T",
            "import ../src/permutation.bend as P",
            "import ../src/lane.bend as L",
            "import ../spec/permutation.bend as F",
            "import ../spec/permutation.bend as S",
            "import ../spec/interleave.bend as I",
            "import ./bits.bend as X", ""]
    return "\n".join(head + body)


# ---------------------------------------------------------------------------
# proofs/sponge.bend

def gen_proofs_sponge():
    TF = lambda b: "True{}" if b else "False{}"
    W = lambda n: ",".join(f"w{i}" for i in range(n))
    FW = lambda n: "".join(f"\n  for +w{i}: U32" for i in range(n))
    comma = lambda n: "".join(f",w{i}" for i in range(n))
    rev = lambda n: "[" + ",".join(f"w{i}" for i in reversed(range(n))) + "]"
    lst = lambda n: "[" + W(n) + "]"
    o = [HEADER, "#",
         "# The public API (src/keccak.bend) against the packed sponge specification",
         "# (spec/sponge.bend): every state the implementation holds is the",
         "# interleaved form (spec/interleave.bend) of the specification's state,",
         "# and the digest is the specification's.",
         "import Base",
         "import ../src/types.bend as T",
         "import ../src/keccak.bend as K",
         "import ../src/permutation.bend as P",
         "import ../src/lane.bend as L",
         "import ../spec/permutation.bend as F",
         "import ../spec/sponge.bend as R",
         "import ../spec/interleave.bend as I",
         "import ./permutation.bend as Q",
         "import ./array.bend as A", ""]
    sp = "T.S{" + ",".join(f"+a{k}" for k in range(25)) + "}"
    xs, ys, ps = [], [], []
    for k in range(25):
        m = TF(k in COMPLEMENTED)
        if k < 17:
            wl, wh = f"w{2 * k}", f"w{2 * k + 1}"
            words = f"(L.even(L.unz({wl}),L.unz({wh})),L.odd(L.unz({wl}),L.unz({wh})))"
            x = f"Q.pxor(Q.mx(Q.il(a{k}),{m}),{words})"
            y = f"Q.mx(Q.il(F.xor(a{k},T.W{{{wl},{wh}}})),{m})"
            mid = f"Q.pxor(Q.mx(Q.il(a{k}),{m}),Q.il(T.W{{{wl},{wh}}}))"
            pf = (f"Equal.trans(U32 & U32,{x},{mid},{y},"
                  f"Q.pxor_cong(Q.mx(Q.il(a{k}),{m}),Q.mx(Q.il(a{k}),{m}),{words},Q.il(T.W{{{wl},{wh}}}),{{==}},Q.words_il({wl},{wh})),"
                  f"Q.xor_il(a{k},T.W{{{wl},{wh}}},{m},False{{}}))")
        else:
            x = y = f"Q.mx(Q.il(a{k}),{m})"
            pf = "{==}"
        xs.append(x)
        ys.append(y)
        ps.append(pf)
    o += ["law mix_correct:", "  for +s: T.State" + FW(34),
          f"  {{L.mix(I.interleave(s),{W(34)}) == I.interleave(R.inject(s,{lst(34)})) : T.St}}", "",
          f"def mix_correct(s,{W(34)}):", "  match s:", f"    case {sp}:",
          "      Q.st_cong(" + ",".join(f"{xs[k]},{ys[k]}" for k in range(25)) + "," + ",".join(ps) + ")", ""]
    o += ["law compress_correct:", "  for +r: Nat", "  for +s: T.State" + FW(34),
          f"  {{P.steps(r,0n,L.mix(I.interleave(s),{W(34)})) == I.interleave(F.rounds(r,0n,R.inject(s,{lst(34)}))) : T.St}}", "",
          f"def compress_correct(r,s,{W(34)}):",
          f"  Equal.trans(T.St,P.steps(r,0n,L.mix(I.interleave(s),{W(34)})),P.steps(r,0n,I.interleave(R.inject(s,{lst(34)}))),I.interleave(F.rounds(r,0n,R.inject(s,{lst(34)}))),",
          f"    Equal.cong(T.St,T.St,t => P.steps(r,0n,t),L.mix(I.interleave(s),{W(34)}),I.interleave(R.inject(s,{lst(34)})),mix_correct(s,{W(34)})),",
          f"    Q.steps_spec(r,0n,R.inject(s,{lst(34)})))", ""]
    o += ["def lift(p: Array<U32> & T.State) -> Array<U32> & T.St:", "  match p:",
          "    case Tuple{a,s}: (a,I.interleave(s))", ""]
    o += ["law read33_correct:", "  for +r: Nat", "  for +index: U32", "  for +s: T.State" + FW(33),
          "  for pair: Array<U32> & U32",
          f"  {{K.read33(r,index,I.interleave(s){comma(33)},pair) == lift(R.gather(r,0n,index,34,False{{}},0n,s,{rev(33)},pair)) : Array<U32> & T.St}}", "",
          f"def read33_correct(r,index,s{comma(33)},pair):", "  (a,w33) = pair",
          f"  Equal.cong(T.St,Array<U32> & T.St,t => (a,t),P.steps(r,0n,L.mix(I.interleave(s),{W(34)})),I.interleave(F.rounds(r,0n,R.inject(s,{lst(34)}))),compress_correct(r,s,{W(34)}))", ""]
    for k in range(32, -1, -1):
        o += [f"law read{k}_correct:", "  for +r: Nat", "  for +index: U32", "  for +s: T.State" + FW(k),
              "  for pair: Array<U32> & U32",
              f"  {{K.read{k}(r,index,I.interleave(s){comma(k)},pair) == lift(R.gather(r,{33 - k}n,index,{k + 1},False{{}},0n,s,{rev(k)},pair)) : Array<U32> & T.St}}", "",
              f"def read{k}_correct(r,index,s{comma(k)},pair):", f"  (a,w{k}) = pair",
              f"  read{k + 1}_correct(r,index,s{comma(k + 1)},Array.get(U32,a,U32.add(index,{k + 1})))", ""]
    padded = ",".join(f"K.pad_word(w{i},{4 * i}n,remain)" for i in range(33)) + ",U32.or(K.pad_word(w33,132n,remain),2147483648)"
    o += ["law padding_correct:", "  for +remain: Nat" + FW(34),
          f"  {{[{padded}] == R.prepare(True{{}},{lst(34)},remain) : List<&2,U32>}}", "",
          f"def padding_correct(remain,{W(34)}):", "  match remain:"]
    o += [f"    case {i}n: {{==}}" for i in range(136)] + ["    case 136n+p: {==}", ""]
    o += ["law padded_correct:", "  for +r: Nat", "  for +remain: Nat", "  for +s: T.State" + FW(34),
          f"  {{P.steps(r,0n,L.mix(I.interleave(s),{padded})) == I.interleave(F.rounds(r,0n,R.inject(s,R.prepare(True{{}},{lst(34)},remain)))) : T.St}}", "",
          f"def padded_correct(r,remain,s,{W(34)}):",
          f"  Equal.trans(T.St,P.steps(r,0n,L.mix(I.interleave(s),{padded})),I.interleave(F.rounds(r,0n,R.inject(s,[{padded}]))),I.interleave(F.rounds(r,0n,R.inject(s,R.prepare(True{{}},{lst(34)},remain)))),",
          f"    compress_correct(r,s,{padded}),",
          f"    Equal.cong(List<&2,U32>,T.St,x => I.interleave(F.rounds(r,0n,R.inject(s,x))),[{padded}],R.prepare(True{{}},{lst(34)},remain),padding_correct(remain,{W(34)})))", ""]
    o += ["law pad33_correct:", "  for +r: Nat", "  for +remain: Nat", "  for +index: U32", "  for +s: T.State" + FW(33),
          "  for pair: Array<U32> & U32",
          f"  {{K.pad33(r,remain,index,I.interleave(s){comma(33)},pair) == I.interleave(Pair.snd(Array<U32>,T.State,R.gather(r,0n,index,34,True{{}},remain,s,{rev(33)},pair))) : T.St}}", "",
          f"def pad33_correct(r,remain,index,s{comma(33)},pair):", "  (a,w33) = pair",
          f"  padded_correct(r,remain,s,{W(34)})", ""]
    for k in range(32, -1, -1):
        o += [f"law pad{k}_correct:", "  for +r: Nat", "  for +remain: Nat", "  for +index: U32", "  for +s: T.State" + FW(k),
              "  for pair: Array<U32> & U32",
              f"  {{K.pad{k}(r,remain,index,I.interleave(s){comma(k)},pair) == I.interleave(Pair.snd(Array<U32>,T.State,R.gather(r,{33 - k}n,index,{k + 1},True{{}},remain,s,{rev(k)},pair))) : T.St}}", "",
              f"def pad{k}_correct(r,remain,index,s{comma(k)},pair):", f"  (a,w{k}) = pair",
              f"  pad{k + 1}_correct(r,remain,index,s{comma(k + 1)},Array.get(U32,a,U32.add(index,{k + 1})))", ""]
    o += SPONGE_TAIL.split("\n")
    L = ["law dig_cong:"]
    for i in range(8):
        L += [f"  for -x{i}: U32", f"  for -y{i}: U32"]
    for i in range(8):
        L.append(f"  for e{i}: {{x{i} == y{i} : U32}}")
    xs8 = ",".join(f"x{i}" for i in range(8))
    ys8 = ",".join(f"y{i}" for i in range(8))
    L.append(f"  {{dig({xs8}) == dig({ys8}) : Array<U32>}}")
    L.append("")
    L.append("def dig_cong(" + ",".join(f"x{i},y{i}" for i in range(8)) + "," + ",".join(f"e{i}" for i in range(8)) + "):")
    for i in range(8):
        cur = [f"x{j}" for j in range(i)] + ["_"] + [f"y{j}" for j in range(i + 1, 8)]
        L.append(f"  %e{i} : {{dig({xs8}) == dig({','.join(cur)}) : Array<U32>}}")
    L += ["  {==}", ""]
    o += L
    args, eqs = [], []
    for k in range(4):
        wk = f"T.W{{x{k},y{k}}}"
        if k in COMPLEMENTED:
            e, od = f"U32.not(U32.not(I.even({wk})))", f"U32.not(U32.not(I.odd({wk})))"
            lo_, hi_ = f"Q.lowc_il(x{k},y{k})", f"Q.highc_il(x{k},y{k})"
        else:
            e, od = f"I.even({wk})", f"I.odd({wk})"
            lo_, hi_ = f"Q.low_il(x{k},y{k})", f"Q.high_il(x{k},y{k})"
        args += [f"L.low({e},{od}),x{k}", f"L.high({e},{od}),y{k}"]
        eqs += [lo_, hi_]
    o += ["law squeeze_correct:", "  for +s: T.State",
          "  {K.digest(L.squeeze(I.interleave(s))) == K.digest(s) : Array<U32>}", "",
          "def squeeze_correct(s):", "  match s:",
          "    case T.S{T.W{+x0,+y0},T.W{+x1,+y1},T.W{+x2,+y2},T.W{+x3,+y3}," + ",".join(f"a{k}" for k in range(4, 25)) + "}:",
          "      dig_cong(" + ",".join(args) + "," + ",".join(eqs) + ")", ""]
    o += API_TAIL.split("\n")
    return "\n".join(o)


SPONGE_TAIL = """law absorb_correct:
  for +r: Nat
  for a: Array<U32>
  for +index: U32
  for +s: T.State
  {K.absorb(r,a,index,I.interleave(s)) == lift(R.absorb(r,a,index,s)) : Array<U32> & T.St}

def absorb_correct(r,a,index,s):
  read0_correct(r,index,s,Array.get(U32,a,index))

law finish_correct:
  for +r: Nat
  for a: Array<U32>
  for +index: U32
  for +remain: Nat
  for +s: T.State
  {K.finish(r,a,index,remain,I.interleave(s)) == I.interleave(R.finish(r,a,index,remain,s)) : T.St}

def finish_correct(r,a,index,remain,s):
  pad0_correct(r,remain,index,s,Array.get(U32,a,index))

law blocks_step:
  for +r: Nat
  for +n: Nat
  for +index: U32
  for +remain: Nat
  for -a: Array<U32>
  for +s: T.State
  for view: Sigma<&2,&1,A.Tree,t => {a == A.thaw(t) : Array<U32>}>
  for recurse: @pair: (Array<U32> & T.State) -> {K.blocks(r,n,U32.add(index,34),remain,lift(pair)) == I.interleave(R.blocks(r,n,U32.add(index,34),remain,pair)) : T.St}
  {K.blocks(r,1n+n,index,remain,lift((a,s))) == I.interleave(R.blocks(r,1n+n,index,remain,(a,s))) : T.St}

def blocks_step(r,n,index,remain,a,s,view,recurse):
  match view:
    case Tuple{+tree,pf}:
      %Equal.sym(Array<U32>,a,A.thaw(tree),pf) : {K.blocks(r,1n+n,index,remain,lift((_,s))) == I.interleave(R.blocks(r,1n+n,index,remain,(_,s))) : T.St}
      Equal.trans(T.St,
        K.blocks(r,n,U32.add(index,34),remain,K.absorb(r,A.thaw(tree),index,I.interleave(s))),
        K.blocks(r,n,U32.add(index,34),remain,lift(R.absorb(r,A.thaw(tree),index,s))),
        I.interleave(R.blocks(r,n,U32.add(index,34),remain,R.absorb(r,A.thaw(tree),index,s))),
        Equal.cong(Array<U32> & T.St,T.St,p => K.blocks(r,n,U32.add(index,34),remain,p),
          K.absorb(r,A.thaw(tree),index,I.interleave(s)),lift(R.absorb(r,A.thaw(tree),index,s)),absorb_correct(r,A.thaw(tree),index,s)),
        recurse(R.absorb(r,A.thaw(tree),index,s)))

law blocks_correct:
  for +r: Nat
  for +n: Nat
  for +index: U32
  for +remain: Nat
  for pair: Array<U32> & T.State
  {K.blocks(r,n,index,remain,lift(pair)) == I.interleave(R.blocks(r,n,index,remain,pair)) : T.St}

def blocks_correct(r,n,index,remain,pair):
  match n pair:
    case 0n Tuple{a,s}: finish_correct(r,a,index,remain,s)
    case 1n+p Tuple{a,s}:
      blocks_step(r,p,index,remain,a,s,A.reify(a),pair => blocks_correct(r,p,U32.add(index,34),remain,pair))

law unchecked_correct:
  for +r: Nat
  for a: Array<U32>
  for +length: Nat
  {K.unchecked(r,a,length) == I.interleave(R.unchecked(r,a,length)) : T.St}

def unchecked_correct(r,a,length):
  blocks_correct(r,Nat.div(length,136n),0,Nat.mod(length,136n),(a,R.initial()))

def dig(+v0: U32, +v1: U32, +v2: U32, +v3: U32, +v4: U32, +v5: U32, +v6: U32, +v7: U32) -> Array<U32>:
  K.digest(T.S{T.W{v0,v1},T.W{v2,v3},T.W{v4,v5},T.W{v6,v7},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0},T.W{0,0}})
"""

API_TAIL = """law digest_correct:
  for +s: T.State
  {K.digest(s) == R.digest(s) : Array<U32>}

def digest_correct(s):
  match s:
    case T.S{T.W{a0,b0},T.W{a1,b1},T.W{a2,b2},T.W{a3,b3},a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24}: {==}

law checked_true_reified:
  for +r: Nat
  for -a: Array<U32>
  for +length: Nat
  for view: Sigma<&2,&1,A.Tree,t => {a == A.thaw(t) : Array<U32>}>
  {K.checked(r,True{},a,length) == R.checked(r,True{},a,length) : Maybe<&1,Array<U32>>}

def checked_true_reified(r,a,length,view):
  match view:
    case Tuple{+tree,pf}:
      %Equal.sym(Array<U32>,a,A.thaw(tree),pf) : {K.checked(r,True{},_,length) == R.checked(r,True{},_,length) : Maybe<&1,Array<U32>>}
      Equal.trans(Maybe<&1,Array<U32>>,
        Some{K.digest(L.squeeze(K.unchecked(r,A.thaw(tree),length)))},
        Some{K.digest(L.squeeze(I.interleave(R.unchecked(r,A.thaw(tree),length))))},
        Some{R.digest(R.unchecked(r,A.thaw(tree),length))},
        Equal.cong(T.St,Maybe<&1,Array<U32>>,t => Some{K.digest(L.squeeze(t))},K.unchecked(r,A.thaw(tree),length),I.interleave(R.unchecked(r,A.thaw(tree),length)),unchecked_correct(r,A.thaw(tree),length)),
      Equal.trans(Maybe<&1,Array<U32>>,
        Some{K.digest(L.squeeze(I.interleave(R.unchecked(r,A.thaw(tree),length))))},
        Some{K.digest(R.unchecked(r,A.thaw(tree),length))},
        Some{R.digest(R.unchecked(r,A.thaw(tree),length))},
        Equal.cong(Array<U32>,Maybe<&1,Array<U32>>,d => Some{d},K.digest(L.squeeze(I.interleave(R.unchecked(r,A.thaw(tree),length)))),K.digest(R.unchecked(r,A.thaw(tree),length)),squeeze_correct(R.unchecked(r,A.thaw(tree),length))),
        Equal.cong(Array<U32>,Maybe<&1,Array<U32>>,d => Some{d},K.digest(R.unchecked(r,A.thaw(tree),length)),R.digest(R.unchecked(r,A.thaw(tree),length)),digest_correct(R.unchecked(r,A.thaw(tree),length)))))

law checked_correct:
  for +r: Nat
  for +valid: Bool
  for a: Array<U32>
  for +length: Nat
  {K.checked(r,valid,a,length) == R.checked(r,valid,a,length) : Maybe<&1,Array<U32>>}

def checked_correct(r,valid,a,length):
  match valid:
    case False{}: {==}
    case True{}: checked_true_reified(r,a,length,A.reify(a))

law sized_correct:
  for +r: Nat
  for +length: Nat
  for pair: Array<U32> & U32
  {K.sized(r,length,pair) == R.sized(r,length,pair) : Maybe<&1,Array<U32>>}

def sized_correct(r,length,pair):
  (a,capacity) = pair
  checked_correct(r,Nat.is_le(length,Nat.mul(4n,U32.to_nat(capacity))),a,length)

law hash_correct:
  for +r: Nat
  for a: Array<U32>
  for +length: Nat
  {K.keccak256_rounds(r,a,length) == R.keccak256_rounds(r,a,length) : Maybe<&1,Array<U32>>}

def hash_correct(r,a,length):
  sized_correct(r,length,Array.size(U32,a))

law ethereum_round_count:
  for a: Array<U32>
  for +length: Nat
  {K.keccak256(a,length) == K.keccak256_rounds(24n,a,length) : Maybe<&1,Array<U32>>}

def ethereum_round_count(a,length): {==}

law public_correct:
  for a: Array<U32>
  for +length: Nat
  {K.keccak256(a,length) == R.keccak256_rounds(24n,a,length) : Maybe<&1,Array<U32>>}

def public_correct(a,length): hash_correct(24n,a,length)
"""


# ---------------------------------------------------------------------------

def main():
    files = {
        "src/permutation.bend": gen_perm(),
        "src/lane.bend": gen_lane(),
        "src/keccak.bend": gen_keccak(),
        "spec/interleave.bend": gen_spec(),
        "proofs/permutation.bend": gen_proofs_perm_file(),
        "proofs/sponge.bend": gen_proofs_sponge(),
    }
    for path, text in files.items():
        (ROOT / path).write_text(text if text.endswith("\n") else text + "\n")


if __name__ == "__main__":
    main()
